{{- if .Values.rbac.create }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aerospike-vector-search.serviceAccountName" . }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "services", "pods"]
    verbs: ["get", "list"]
{{- end }}

{{- if .Values.rbac.create }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aerospike-vector-search.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aerospike-vector-search.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aerospike-vector-search.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
