---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aerospike-vector-search.fullname" . }}-internal
  labels:
    app:  {{ include "aerospike-vector-search.fullname" . }}
    {{- include "aerospike-vector-search.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range $k := .Values.aerospikeVectorSearchConfig.service.ports | keys }}
    - name: {{ printf "svc-%s" $k }}
      appProtocol: grpc
      port: {{ $k }}
      {{- end -}}
    {{- range $k := .Values.aerospikeVectorSearchConfig.manage.ports | keys }}
    - name: {{ printf "manage-%s" $k }}
      appProtocol: http
      port: {{ $k }}
      {{- end -}}
    {{- range $k := .Values.aerospikeVectorSearchConfig.interconnect.ports | keys }}
    - name: {{ printf "interc-%s" $k }}
      port: {{ $k }}
      {{- end }}
  selector:
    app:  {{ include "aerospike-vector-search.fullname" . }}
    {{- include "aerospike-vector-search.selectorLabels" . | nindent 4 }}


{{- if and .Values.service.enabled  -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aerospike-vector-search.fullname" . }}
  labels:
    {{- include "aerospike-vector-search.labels" . | nindent 4 }}
    app: {{ include "aerospike-vector-search.fullname" . }}
  {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with .Values.service.allocateLoadBalancerNodePorts }}
  allocateLoadBalancerNodePorts: {{ . }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with .Values.service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- if semverCompare ">=1.21.0-0" .Capabilities.KubeVersion.Version }}
    {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
    {{- end }}
    {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  ports:
    {{- range $index, $port := .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      protocol: {{ $port.protocol | default "TCP" }}
      {{- with $port.targetPort }}
      targetPort: {{ . }}
      {{- end }}
      {{- if and (semverCompare ">=1.20" $.Capabilities.KubeVersion.Version) $port.appProtocol }}
      appProtocol: {{ $port.appProtocol }}
      {{- end }}
      {{- if (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) }}
      nodePort: {{ $port.nodePort | default nil }}
      {{- end }}
    {{- end }}
  selector:
    app: {{ include "aerospike-vector-search.fullname" . }}
    {{- include "aerospike-vector-search.selectorLabels" . | nindent 4 }}
{{- end }}
