replicaCount: 3
aerospikeVectorSearchConfig:
  cluster:
    cluster-name: "avs-db-1"
  feature-key-file: "/etc/aerospike-vector-search/secrets/features.conf"
  service:
    metadata-namespace: "avs-meta"
    ports:
      5000: { }
  manage:
    ports:
      5040: { }

  heartbeat:
    seeds:
      - address: avs-app-aerospike-vector-search-0.avs-app-aerospike-vector-search-internal.aerospike.svc.cluster.local
        port: 5001
  interconnect:
    ports:
      5001:
        addresses:
          "0.0.0.0"

  storage:
    client-policy: {}
    seeds:
      - aerocluster-0-0.aerocluster.aerospike.svc.cluster.local:
          port: 3000
  logging:
    enable-console-logging: false
    format: simple
    max-history: 30
    levels:
      metrics-ticker: debug
      root: info
    ticker-interval: 10

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 0
image:
  repository: "aerospike/aerospike-vector-search"
  pullPolicy: "IfNotPresent"
  tag: "1.0.0"

initContainer:
  image:
    repository: davi17g/avs-init-container
    tag: "4.0.5"
    pullPolicy: Always

aerospikeVectorSearchNodeRoles:
  node-label-1:
    - query
  node-label-2:
    - query
    - index-update

serviceAccount:
  create: true

service:
  enabled: true
  type: NodePort
  ports:
    - name: "svc-5000"
      port: 5000
      targetPort: 5000
      nodePort: 30036
