---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aerospike-vector-search.serviceAccountName" . }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aerospike-vector-search.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aerospike-vector-search.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    {{ if .Values.serviceAccount.create }}
    name: {{ include "aerospike-vector-search.serviceAccountName" . }}
    {{ else }}
    name: default
    {{- end }}
    namespace: {{ .Release.Namespace }}
