replicaCount: 3
aerospikeVectorSearchConfig:
  cluster:
    cluster-name: "avs-db-1"
  feature-key-file: "/etc/aerospike-vector-search/secrets/features.conf"
  service:
    metadata-namespace: "avs-meta"
    ports:
      5000:
        addresses:
          "0.0.0.0"
        # tls-id: service-tls
  manage:
    ports:
      5040: { }

  heartbeat:
    seeds:
      - address: avs-app-aerospike-vector-search-0.avs-app-aerospike-vector-search.aerospike.svc.cluster.local
        port: 5001
  interconnect:
    # client-tls-id: interconnect-tls
    ports:
      5001:
        addresses:
          "0.0.0.0"
        # tls-id: interconnect-tls
  storage:
    client-policy: {}
    seeds:
      - aerocluster-0-0.aerocluster.aerospike.svc.cluster.local:
          port: 3000
  logging:
    #    file: /var/log/aerospike-vector-search/aerospike-vector-search.log
    enable-console-logging: false
    format: simple
    max-history: 30
    levels:
      metrics-ticker: debug
      root: info
    ticker-interval: 10

aerospikeVectorSearchNodeRoles:
  node-label-1:
    - query
  node-label-2:
    - query
    - index-update

serviceAccount:
  create: true

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 0
image:
  repository: "aerospike/aerospike-vector-search"
  pullPolicy: "IfNotPresent"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"
extraSecretVolumeMounts:
  - name: aerospike-tls
    mountPath: "/etc/ssl/certs"
    readOnly: true

extraVolumes:
  - name: aerospike-tls
    secret:
      secretName: aerospike-tls
      optional: false
affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: aerospike.com/node-pool
            operator: In
            values:
            - "avs"
