name: Test init container (unit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        cd helm-aerospike-vector-search/avs-init-container/cmd
        go mod download

    - name: Run tests
      run: |
        cd helm-aerospike-vector-search/avs-init-container/cmd
        go test -v ./...